import Head from 'next/head'
import Image from 'next/image'
import { useContext } from 'react'
import styles from '../styles/Home.module.css'
import Quizbuilder from './quizbuilder'
import quizbuilder from './quizbuilder'

export default function Home() {
  // const context = useContext()

  return (
    <div className={styles.container}>
      <Head>
        <title>Q project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
         <Quizbuilder />
     </div>
  )
}
