import Head from 'next/head'
import Image from 'next/image'
import { useContext } from 'react'
import styles from '../styles/Home.module.css'
import Dashboard from './dashbord'
import Quizbuilder from './quizbuilder'
import quizbuilder from './quizbuilder'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Q project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dashboard />
    </div>
  )
}

// Dashbord/quiz/id
// => Preview Quiz

// After preview => Share Btn
// Redirect to Domain/userName/quiz/id
// => Reuser Preview Component for taking quiz
